### ISSUE TITLE
Add this to appstore

### ISSUE THREAD

**Issue by Skalke** [Sciguy429/KipSelect#3]
https://switchbru.com/appstore/#/

**Comment by Sciguy429** [comment]
Ah yes, I was going to do this when I had the project finalized, if you want I can build a quick beta version to put on the store in the time being, I've just been to busy with life recently to get any further with this project :P

**Comment by Sciguy429** [comment]
Alright i've sent it off the the appstore, thanks for the reminder

**Comment by Sciguy429** [comment]
Well that was fast:

https://www.switchbru.com/appstore/#/app/KipSelect
