### ISSUE TITLE
Suggestion: Implement reboot to RCM/payload like atmosphere

### ISSUE THREAD

**Issue by tiliarou** [Sciguy429/KipSelect#5]
Use the new homebrew code within latest atmo repo commits to implement a reboot to RCM and/or payload so as to load the enabled keep, directly from KipSelect.

[https://github.com/Atmosphere-NX/Atmosphere/blob/f99dea798a6bdfc3e812b8feb689ded58925b4cd/troposphere/reboot_to_payload/source/main.c](https://github.com/Atmosphere-NX/Atmosphere/blob/f99dea798a6bdfc3e812b8feb689ded58925b4cd/troposphere/reboot_to_payload/source/main.c)

**Comment by Sciguy429** [comment]
Oh wow I didn't even see that in the changelog, that is actually really cool. Shouldn't be to hard to set up.

**Comment by Sciguy429** [comment]
Well that was easy....

[https://youtu.be/HEnTUdD-7tg](url)

**Comment by tiliarou** [comment]
thanks !

**Comment by tiliarou** [comment]
@Sciguy429 Just one thing: the current crash trigger is actually meant to be. It's one of the easiest way to trigger the reboot to payload from IRAM.
Some devs are working on actually providing a seamless way to reboot with a simple button. (I believe Xortroll in Goldleaf, and something might come in Kosmos as well).

**Comment by Sciguy429** [comment]
@tiliarou I assumed as much, it was just confusing at first. I though I had coded it wrong.
