### ISSUE TITLE
Reboot Crash Advice

### ISSUE THREAD

**Issue by 00mn00** [Sciguy429/KipSelect#6]
If you're looking to understand how to reboot to payload without triggering a crash, you might consider looking at - https://github.com/wf-/ShutdownMenu - and seeing how they do it. Thanks for the great tool, works a treat.

**Comment by Sciguy429** [comment]
You are welcome :D and belive me you are haveing a better time than I am today. Yesterday literly about 5 minutes after I Pushed the new release my PC died and now I'm stuck at home with the worst stomach flu I've ever had. Have fun with KipSelect and be glad your not me today
