### ISSUE TITLE
Add more titles in description

### ISSUE THREAD

**Issue by Skalke** [Sciguy429/KipSelect#7]
For example 
00FF0000636C6BFF - Overclock Module by @m4xw 
https://github.com/retronx-team/sys-clk/releases

And 

00FF747765616BFF - supernag patcher for BrowseNX by @crc-32
https://github.com/crc-32/BrowseNX/releases

It will be better to read and manage titleid for advanced but forgetful users.

**Comment by m4xw** [comment]
Supernag "patcher" is sys-tweak by @p-sam 
https://github.com/p-sam/switch-sys-tweak

**Comment by p-sam** [comment]
btw 636C6B is 63 6C 6B chars, which is "clk"
747765616B -> 74 77 65 61 6B  -> "tweak"

**Comment by Sciguy429** [comment]
This is actuly something I had planned to do for awhile. The only problem is there's not really a compleate list of system modules out there. If anyone's got a list like that I would be happy to set this up for the next update.

**Comment by TheLastZombie** [comment]
Might as well add to this, anything's better than nothing:

**010000000000000D:** [dmnt](https://github.com/Atmosphere-NX/Atmosphere/tree/master/stratosphere/dmnt)
**0100000000000352:** [emuiibo](https://github.com/xortroll/emuiibo)
**0100000000000464:** [SwitchPresence-Rewritten](https://github.com/SunTheCourier/SwitchPresence-Rewritten)
**0100000000000FAF:** [hid-mitm](https://github.com/jakibaki/hid-mitm)
**010000000000C235:** [Freebird](https://gbatemp.net/threads/freebird-switch-clock-speed-control-sysmodule.530641/)
**010041544D530000:** [ams-mitm](https://github.com/Atmosphere-NX/Atmosphere/tree/master/stratosphere/ams_mitm)
**31200000000000AB:** [xor.play](https://github.com/XorTroll/ModuleMania/tree/master/xor.play)
**4200000000000000:** [nx-dreport](https://github.com/Thog/nx-dreport)
**4200000000000000:** [sys-audioplayer](https://github.com/jakibaki/sys-audioplayer)
**420000000000000E:** [sys-ftpd](https://github.com/jakibaki/sys-ftpd)
**420000000000000F:** [SlideNX](https://github.com/jonyluke/SlideNX)
**420000000000001E:** [SwitchPresence](https://github.com/Random0666/SwitchPresence)
**430000000000000A:** [sys-netcheat](https://github.com/jakibaki/sys-netcheat)

**Comment by TheLastZombie** [comment]
**0100000000000FAF:** [hid-mitm](https://github.com/jakibaki/hid-mitm)
**010000000000C235:** [Freebird](https://gbatemp.net/threads/freebird-switch-clock-speed-control-sysmodule.530641/)
**31200000000000AB:** [xor.play](https://github.com/XorTroll/ModuleMania/tree/master/xor.play)
**4200000000000000:** [nx-dreport](https://github.com/Thog/nx-dreport)
**4200000000000000:** [sys-audioplayer](https://github.com/jakibaki/sys-audioplayer)
**420000000000000E:** [sys-ftpd](https://github.com/jakibaki/sys-ftpd)
**420000000000000F:** [SlideNX](https://github.com/jonyluke/SlideNX)
**420000000000001E:** [SwitchPresence](https://github.com/Random0666/SwitchPresence)
**430000000000000A:** [sys-netcheat](https://github.com/jakibaki/sys-netcheat)

**Comment by Skalke** [comment]
**4200000000000010:** [ldn_mitm](https://github.com/spacemeowx2/ldn_mitm/releases)

**Comment by Sciguy429** [comment]
Wow, I didn't think people were still using this thing anymore.

Well here to make this easier, add any system-modules you want the tool to know about to this google form:

[Google Form](https://forms.gle/uCk3YqHWRxUX7feU6)

Ill see what I can do, college takes up most of my free time as of now, It might be awhile.

**Comment by Sciguy429** [comment]
Here's a spreadsheet of whats been submitted so far:

https://docs.google.com/spreadsheets/d/1maCxhz6OS9SAy412IkFEe1ssicqoFoZb8mYhgifTFzY/edit?usp=sharing

**Comment by Sciguy429** [comment]
Alright so I finally got around to setting this up. Keep in mind though, this only works with system modules, not KIPS. If anyone wants to test this out for me that would be awesome, I don't have the time to extensively crash test.


[Kip_Select.zip](https://github.com/Sciguy429/KipSelect/files/3730137/Kip_Select.zip)
(Sorry about the zip file, Github won't let me just upload the .nro)

**Comment by Sciguy429** [comment]
Support added in latest release, 3.1.0
